# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gopage_pb2 as gopage__pb2


class GopageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get1 = channel.unary_unary(
        '/gopage.Gopage/get1',
        request_serializer=gopage__pb2.GetParams.SerializeToString,
        response_deserializer=gopage__pb2.Number.FromString,
        )
    self.get2 = channel.unary_unary(
        '/gopage.Gopage/get2',
        request_serializer=gopage__pb2.GetParams.SerializeToString,
        response_deserializer=gopage__pb2.Number.FromString,
        )


class GopageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get1(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get2(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GopageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get1': grpc.unary_unary_rpc_method_handler(
          servicer.get1,
          request_deserializer=gopage__pb2.GetParams.FromString,
          response_serializer=gopage__pb2.Number.SerializeToString,
      ),
      'get2': grpc.unary_unary_rpc_method_handler(
          servicer.get2,
          request_deserializer=gopage__pb2.GetParams.FromString,
          response_serializer=gopage__pb2.Number.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gopage.Gopage', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
