# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gopage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gopage.proto',
  package='gopage',
  syntax='proto3',
  serialized_pb=_b('\n\x0cgopage.proto\x12\x06gopage\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\"\x0b\n\tGetParams2b\n\x06Gopage\x12+\n\x04get1\x12\x11.gopage.GetParams\x1a\x0e.gopage.Number\"\x00\x12+\n\x04get2\x12\x11.gopage.GetParams\x1a\x0e.gopage.Number\"\x00\x62\x06proto3')
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='gopage.Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='gopage.Number.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=47,
)


_GETPARAMS = _descriptor.Descriptor(
  name='GetParams',
  full_name='gopage.GetParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['GetParams'] = _GETPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'gopage_pb2'
  # @@protoc_insertion_point(class_scope:gopage.Number)
  ))
_sym_db.RegisterMessage(Number)

GetParams = _reflection.GeneratedProtocolMessageType('GetParams', (_message.Message,), dict(
  DESCRIPTOR = _GETPARAMS,
  __module__ = 'gopage_pb2'
  # @@protoc_insertion_point(class_scope:gopage.GetParams)
  ))
_sym_db.RegisterMessage(GetParams)



_GOPAGE = _descriptor.ServiceDescriptor(
  name='Gopage',
  full_name='gopage.Gopage',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=62,
  serialized_end=160,
  methods=[
  _descriptor.MethodDescriptor(
    name='get1',
    full_name='gopage.Gopage.get1',
    index=0,
    containing_service=None,
    input_type=_GETPARAMS,
    output_type=_NUMBER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get2',
    full_name='gopage.Gopage.get2',
    index=1,
    containing_service=None,
    input_type=_GETPARAMS,
    output_type=_NUMBER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GOPAGE)

DESCRIPTOR.services_by_name['Gopage'] = _GOPAGE

# @@protoc_insertion_point(module_scope)
